language: python
deploy:
  provider: heroku
  api_key:
    secure: fa08ea17-ce58-48d0-81c2-81731aeb9141
  app: textbooks-exchange
services:
  - postgresql
before_script:
  - psql -c "create user postgres with password 'password';" -U postgres
  - psql -c 'alter user test createdb;' -U postgres
script:
  python manage.py test